<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Mega Triananda Putri">
<meta name="dcterms.date" content="2024-01-19">

<title>Pengaruh Kemiskinan Terhadap Stunting di Indonesia</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="index.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Pengaruh Kemiskinan Terhadap Stunting di Indonesia</h1>
<p class="subtitle lead">Metode Penelitian Politeknik APP Jakarta</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Mega Triananda Putri </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 19, 2024</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<p><img src="poltekapp.jpg" class="img-fluid"></p>
<section id="pendahuluan" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="pendahuluan"><span class="header-section-number">1</span> Pendahuluan</h2>
<section id="latar-belakang" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="latar-belakang"><span class="header-section-number">1.1</span> Latar belakang</h3>
<p>Stunting adalah kondisi gagal tumbuh pada anak akibat kekurangan gizi dalam waktu yang lama, yang menyebabkan tinggi badan anak lebih pendek dari standar usianya. Stunting dapat mengganggu perkembangan otak dan kognitif anak, serta meningkatkan risiko penyakit kronis dan rendahnya produktivitas di masa depan.</p>
<p>Salah satu faktor yang berpengaruh terhadap stunting adalah kemiskinan. Kemiskinan dapat membatasi akses keluarga terhadap makanan bergizi, sanitasi yang layak, air bersih, dan pelayanan kesehatan. Data BPS tahun 2019 menunjukkan bahwa sebagian besar anak stunting berasal dari keluarga yang tergolong miskin atau berada di bawah garis kemiskinan. Selain itu, terdapat korelasi positif antara tingkat kemiskinan dan prevalensi stunting di setiap provinsi di Indonesia, yang berarti semakin tinggi tingkat kemiskinan, semakin tinggi pula prevalensi stunting, dan sebaliknya. Oleh karena itu, upaya penurunan kemiskinan perlu menjadi prioritas dalam penanganan stunting di Indonesia.</p>
<p>Berdasarkan uraian di atas, maka penelitian ini bertujuan untuk menganalisis pengaruh kemiskinan terhadap stunting di Indonesia, dengan menggunakan data sekunder dari BPS, Kementerian Kesehatan, dan sumber lain yang relevan. Penelitian ini diharapkan dapat memberikan kontribusi dalam mengidentifikasi faktor-faktor yang memengaruhi stunting, serta memberikan rekomendasi kebijakan yang tepat untuk mengatasi permasalahan stunting dan kemiskinan di Indonesia.</p>
</section>
<section id="ruang-lingkup" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="ruang-lingkup"><span class="header-section-number">1.2</span> Ruang lingkup</h3>
<p>Penelitian ini menggunakan data stunting sebagai variabel y, yang didapatkan dari Hasil Survey Status Gizi Indonesia (SSGI) Kementerian Kesehatan. Serta data persentase penduduk miskin, dari Badan Pusat Statistik (BPS). Peneliti mengambil data dari 34 provinsi di Indonesia pada periode tahun 2022.</p>
</section>
<section id="rumusan-masalah" class="level3" data-number="1.3">
<h3 data-number="1.3" class="anchored" data-anchor-id="rumusan-masalah"><span class="header-section-number">1.3</span> Rumusan masalah</h3>
<ol type="1">
<li><p>Apakah kemiskinan mempengaruhi stunting pada anak Indonesia ?</p></li>
<li><p>Bagaimana hubungan kemiskinan terhadap stunting?</p></li>
</ol>
</section>
<section id="tujuan-dan-manfaat-penelitian" class="level3" data-number="1.4">
<h3 data-number="1.4" class="anchored" data-anchor-id="tujuan-dan-manfaat-penelitian"><span class="header-section-number">1.4</span> Tujuan dan manfaat penelitian</h3>
<p>Penelitian ini bertujuan untuk mempelajari korelasi antara kemiskinan dan stunting. Penelitian ini diharapkan dapat memberikan manfaat bagi berbagai pihak, yaitu:</p>
<p>Pemerintah: Penelitian ini dapat menjadi acuan bagi pemerintah untuk membuat kebijakan yang efektif untuk menanggulangi stunting.</p>
<p>Lembaga Swadaya Masyarakat (LSM) : Penelitian ini dapat menjadi bahan bagi LSM untuk merancang program yang sesuai untuk menanggulangi stunting.</p>
<p>Masyarakat: Penelitian ini dapat menumbuhkan kesadaran masyarakat tentang urgensi untuk menanggulangi stunting.</p>
<p>Secara spesifik, penelitian ini bertujuan untuk menemukan faktor kemiskinan yang mempengaruhi stunting, mengetahui tingkat kejadian stunting pada keluarga miskin, mengukur korelasi antara kemiskinan dan stunting.</p>
</section>
<section id="package" class="level3" data-number="1.5">
<h3 data-number="1.5" class="anchored" data-anchor-id="package"><span class="header-section-number">1.5</span> Package</h3>
<p>Packages yang digunakan antara lain sebagai berikut:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(writexl)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="studi-pustaka" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="studi-pustaka"><span class="header-section-number">2</span> Studi pustaka</h2>
<p><strong>Kemiskinan</strong></p>
<p>Kemiskinan adalah keadaan saat seseorang atau sekelompok orang tidak mampu memenuhi kebutuhan dasar seperti makanan, pakaian, tempat berlindung, pendidikan, dan kesehatan. Kemiskinan dapat disebabkan oleh berbagai faktor, seperti kelangkaan sumber daya, ketidakadilan sosial, konflik, bencana, atau penyakit. Kemiskinan dapat dikelompokkan menjadi dua jenis, yaitu kemiskinan absolut dan kemiskinan relatif. Kemiskinan absolut mengacu pada kondisi di mana seseorang tidak memiliki cukuo penghasilan untuk membeli kebutuhan minimum yang ditetapkan oleh suatu standar. Kemiskinan relative mengacu pada kondisi di mana seseorang memiliki penghasilan yang lebih rendah daripada rata-rata penduduk suatu negara atau wilayah.</p>
<p>Kemiskinan memiliki dampak negatif bagi individu, keluarga, masyarakat, dan negara. Kemiskinan dapat menurunkan kualitas hidup, kesehatan, pendidikan, dan peluang ekonomi. Kemiskinan juga dapat meningkatkan risiko kekerasan, kriminalitas, diskriminasi, dan marginalisasi. Kemiskinan dapat memperburuk masalah lingkungan, seperti degradasi tanah, deforestasi, polusi, dan perubahan iklim. Kemiskinan dapat menghambat pembangunan manusia, sosial, dan ekonomi.</p>
<p>Untuk mengatasi kemiskinan, diperlukan upaya bersama dari berbagai pihak. Pemerintah, swasta, masyarakat sipil, organisasi internasional, dan individu harus turut andil dalam pemberantasan kemiskinan.</p>
<p><strong>Stunting</strong></p>
<p>Stunting merupakan salah satu masalah gizi kronis yang diakibatkan oleh kurangnya asupan gizi pada anak dalam jangka waktu panjang sehingga menyebabkan terhambatnya pertumbuhan. Masalah gizi satu ini menjadi penyebab mengapa anak memiliki tinggi badan di bawah standar anak seusianya karena pada dasarnya stunting sendiri menghambat pertumbuhan tinggi anak. Stunting sendiri biasanya terjadi ketika anak masih dalam kandungan dan mulai terlihat ketika mereka memasuki usia dua tahun.</p>
<p>Beberapa gejala yang menandai anak terkena stunting seperti wajah tampak lebih muda dari anak seusianya, pertumbuhan gigi dan tubuh yang terlambat, kemampuan focus dan memori belajar yang buruk, pubertas yang lambat, berat badan lebih ringan dari anak seusianya, dan banyak lagi.</p>
<p>Kementrian Kesehatan menyatakan dengan tegas bahwa stunting adalah ancaman utama terhadap kualitas sumer daya manusia yang dimiliki Indonesia. Hal ini disebabkan karena stunting tidak hanya mengganggu pertumbuhan fisik, tetapi juga mengganggu pertumbuhan otak sehingga memengaruhi kemampuan dan prestasi anak. Di samping itu, anak dengan stunting biasanya juga memiliki riwayat kesehatan yang kurang baik karena daya tahan tubuh yang buruk. Stunting dapat menjadi kelainan turun menurun apabila tidak cepat ditangani.</p>
</section>
<section id="metode-penelitian" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="metode-penelitian"><span class="header-section-number">3</span> Metode penelitian</h2>
<section id="data" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="data"><span class="header-section-number">3.1</span> Data</h3>
<table class="table">
<thead>
<tr class="header">
<th></th>
<th>Provinsi</th>
<th>x</th>
<th>y</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Nusa Tenggara Timur</td>
<td>20,23</td>
<td>35,30</td>
</tr>
<tr class="even">
<td>2</td>
<td>Sulawesi Barat</td>
<td>13,76</td>
<td>35,00000</td>
</tr>
<tr class="odd">
<td>3</td>
<td>Papua</td>
<td>26,8</td>
<td>34,600</td>
</tr>
<tr class="even">
<td>4</td>
<td>Nusa Tenggara Barat</td>
<td>13,82</td>
<td>32,70</td>
</tr>
<tr class="odd">
<td>5</td>
<td>Aceh</td>
<td>14,75</td>
<td>31,2</td>
</tr>
<tr class="even">
<td>6</td>
<td>Papua Barat</td>
<td>21,43</td>
<td>30,00</td>
</tr>
<tr class="odd">
<td>7</td>
<td>Sulawesi Tengah</td>
<td>12,41</td>
<td>28,20</td>
</tr>
<tr class="even">
<td>8</td>
<td>Kalimantan Barat</td>
<td>11,11</td>
<td>27,80</td>
</tr>
<tr class="odd">
<td>9</td>
<td>Sulawesi Tenggara</td>
<td>7,4</td>
<td>28</td>
</tr>
<tr class="even">
<td>10</td>
<td>Sulawesi Selatan</td>
<td>8,7</td>
<td>27,20</td>
</tr>
<tr class="odd">
<td>11</td>
<td>Kalimantan Tengah</td>
<td>5,11</td>
<td>26,90</td>
</tr>
<tr class="even">
<td>12</td>
<td>Maluku Utara</td>
<td>6,46</td>
<td>26,10</td>
</tr>
<tr class="odd">
<td>13</td>
<td>Maluku</td>
<td>16,23</td>
<td>26,10</td>
</tr>
<tr class="even">
<td>14</td>
<td>Sumatera Barat</td>
<td>5,95</td>
<td>25,20</td>
</tr>
<tr class="odd">
<td>15</td>
<td>Kalimantan Selatan</td>
<td>4,29</td>
<td>24,60</td>
</tr>
<tr class="even">
<td>16</td>
<td>Kalimantan Timur</td>
<td>6,11</td>
<td>23,90</td>
</tr>
<tr class="odd">
<td>17</td>
<td>Gorontalo</td>
<td>15,51</td>
<td>23,80</td>
</tr>
<tr class="even">
<td>18</td>
<td>Kalimantan Utara</td>
<td>6,45</td>
<td>22,10</td>
</tr>
<tr class="odd">
<td>19</td>
<td>Sumatera Utara</td>
<td>8,15</td>
<td>21,10</td>
</tr>
<tr class="even">
<td>20</td>
<td>Jawa Tengah</td>
<td>10,77</td>
<td>20,80</td>
</tr>
<tr class="odd">
<td>21</td>
<td>Sulawesi Utara</td>
<td>7,38</td>
<td>20,50</td>
</tr>
<tr class="even">
<td>22</td>
<td>Jawa Barat</td>
<td>7,62</td>
<td>20,20</td>
</tr>
<tr class="odd">
<td>23</td>
<td>Banten</td>
<td>6,17</td>
<td>20,00</td>
</tr>
<tr class="even">
<td>24</td>
<td>Bengkulu</td>
<td>14,34</td>
<td>19,80</td>
</tr>
<tr class="odd">
<td>25</td>
<td>Jawa Timur</td>
<td>7,5</td>
<td>19,20</td>
</tr>
<tr class="even">
<td>26</td>
<td>Sumatera Selatan</td>
<td>11,78</td>
<td>18,60</td>
</tr>
<tr class="odd">
<td>27</td>
<td>Kep Bangka Belitung</td>
<td>4,52</td>
<td>18,50</td>
</tr>
<tr class="even">
<td>28</td>
<td>Jambi</td>
<td>10,19</td>
<td>18,00</td>
</tr>
<tr class="odd">
<td>29</td>
<td>Riau</td>
<td>6,68</td>
<td>17,00</td>
</tr>
<tr class="even">
<td>30</td>
<td>DI Yogyakarta</td>
<td>11,04</td>
<td>16,40</td>
</tr>
<tr class="odd">
<td>31</td>
<td>Kepulauan Riau</td>
<td>5,69</td>
<td>15,40</td>
</tr>
<tr class="even">
<td>32</td>
<td>Lampung</td>
<td>8,02</td>
<td>15,20</td>
</tr>
<tr class="odd">
<td>33</td>
<td>DKI Jakarta</td>
<td>4,44</td>
<td>14,80</td>
</tr>
<tr class="even">
<td>34</td>
<td>Bali</td>
<td>4,25</td>
<td>8,00</td>
</tr>
</tbody>
</table>
<p>penelitian ini menggunakan data sekunder dari 34 provinsi di Indonesia tahun 2022 dalam satuan persen. Dimana variabel x berupa “persentase penduduk miskin”, dan variabel y sebagai persentase “stunting”. Data inilah yang nantinya akan digunakan sebagai objek penelitian.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co">#import dataset</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>stunting<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">'stunting.xlsx'</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(stunting)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  Provinsi                x     y
  &lt;chr&gt;               &lt;dbl&gt; &lt;dbl&gt;
1 Nusa Tenggara Timur  20.2  35.3
2 Sulawesi Barat       13.8  35  
3 Papua                26.8  34.6
4 Nusa Tenggara Barat  13.8  32.7
5 Aceh                 14.8  31.2
6 Papua Barat          21.4  30  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-mpg</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Hubungan antara kemiskinan dan stunting"</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"ggplot2"</span>)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"readxl"</span>)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"dplyr"</span>)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>stunting,<span class="fu">aes</span>(<span class="at">x=</span>x,<span class="at">y=</span>y)) <span class="sc">+</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color=</span><span class="st">"plum"</span>,<span class="at">size=</span><span class="dv">2</span>) <span class="sc">+</span> </span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"hubungan kemiskinan dan stunting"</span>,</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">x=</span><span class="st">"kemiskinan(%)"</span>,</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">y=</span><span class="st">"stunting(%)"</span>,</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"sumber: Survey Status Gizi Indonesia (SSGI), Badan Pusat Statistik"</span>) <span class="sc">+</span></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="metode-analisis" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="metode-analisis"><span class="header-section-number">3.2</span> Metode analisis</h3>
<p>Dalam penelitian ini metode yang akan digunakan adalah regresi univariat, dengan data kemiskinan sebagai variabel independent. Penelitian ini bermaksud untuk mencari hubungan antara kemiskinan dan stunting, dengan spesifikasi yang dilakukan sebagai berikut:</p>
<p><span class="math display">\[
y_{t}=\beta_0 + \beta_1 x_t+\mu_t
\]</span> di mana <span class="math inline">\(y_t\)</span> adalah stunting dan <span class="math inline">\(x_t\)</span> adalah kemiskinan.</p>
</section>
</section>
<section id="pembahasan" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="pembahasan"><span class="header-section-number">4</span> Pembahasan</h2>
<section id="pembahasan-masalah" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="pembahasan-masalah"><span class="header-section-number">4.1</span> Pembahasan masalah</h3>
<p>Setelah dilakukan regresi, dihasilkan data sebagai berikut:</p>
<table class="table">
<thead>
<tr class="header">
<th>Coefficients:</th>
<th>P</th>
<th>Estimate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept</td>
<td>2.01e-09</td>
<td>15.5577</td>
</tr>
<tr class="even">
<td>x</td>
<td>5.88e-05</td>
<td>0.7620</td>
</tr>
</tbody>
</table>
<p><span class="math display">\[
y_{t}=\ 15.5577  + \ 0.7620  x+\mu_t
\]</span></p>
<p>Nilai dari koefisien x (0.7620) menunjukkan bahwa setiap kenaikan satu kemiskinan akan meningkatkan stunting sebesar 0.7620. maka begitu pula sebaliknya, jika kemiskinan turun satu akan menurunkan stunting sebesar 0.7620. Selain itu nilai koefisien ini juga signifikan secara statistic, yang ditunjukkan dari nilai p sebesar 5.88e-05 kurang dari alpaha (0,05).</p>
<p>Beberapa hal yang menggambarkan keterkaitan kekurangan ekonomi dengan stunting:</p>
<p><strong>a. Keterbatasan dalam mengakses makanan bergizi</strong></p>
<p>Keluarga miskin cenderung memiliki penghasilan yang lebih rendah, sehingga mereka tidak mampu membeli makanan bergizi yang cukup untuk memenuhi kebutuhan gizi anak.</p>
<p><strong>b. Keterbatasan dalam mengakses sarana Kesehatan</strong></p>
<p>Keluarga miskin cenderung memiliki keterbatasan dalam mengakses sarana kesehatan, sehingga mereka tidak dapat memanfaatkan layanan kesehatan yang dibutuhkan untuk mencegah dan mengatasi stunting.</p>
</section>
<section id="analisis-masalah" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="analisis-masalah"><span class="header-section-number">4.2</span> Analisis masalah</h3>
<p>Hasil regresinya adalah</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>dat<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">"stunting.xlsx"</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>reg<span class="ot">&lt;-</span><span class="fu">lm</span>(y<span class="sc">~</span>x,<span class="at">data=</span>stunting)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ x, data = stunting)

Residuals:
     Min       1Q   Median       3Q      Max 
-10.7962  -3.6300  -0.6747   4.3837   8.9571 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  15.5577     1.8859   8.250 2.01e-09 ***
x             0.7620     0.1647   4.626 5.88e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5.088 on 32 degrees of freedom
Multiple R-squared:  0.4007,    Adjusted R-squared:  0.382 
F-statistic:  21.4 on 1 and 32 DF,  p-value: 5.877e-05</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>stunting<span class="sc">$</span>m<span class="ot">&lt;-</span><span class="fu">resid</span>(reg)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(stunting<span class="sc">$</span>y,stunting<span class="sc">$</span>m,<span class="at">xlab =</span> <span class="st">"stunting"</span>,<span class="at">ylab =</span> <span class="st">"error"</span>,<span class="at">col=</span><span class="st">'violet'</span>)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>plot pengaruh error terhadap stunting</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>stunting<span class="sc">$</span>m<span class="ot">&lt;-</span><span class="fu">resid</span>(reg)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(stunting<span class="sc">$</span>x,stunting<span class="sc">$</span>m,<span class="at">xlab =</span> <span class="st">"kemiskinan"</span>,<span class="at">ylab =</span> <span class="st">"error"</span>,<span class="at">col=</span><span class="st">'coral'</span>)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>plot pengaruh error terhadap kemiskinan</p>
<p>Nilai R-squared (0.4007) artinya variabel x dapat menjelaskan 40.07% perubahan y. Selain itu nilai F-statistik adalah 21.4, dengan p-value 5.877e-05, yang lebih kecil dari α=0.05, yang berarti variabel x berpengaruh signifikan terhadap variabel y secara simultan.</p>
</section>
</section>
<section id="kesimpulan" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="kesimpulan"><span class="header-section-number">5</span> Kesimpulan</h2>
<p>Kemiskinan memiliki pengaruh yang signifikan terhadap stunting di Indonesia, hal ini dapat dilihat dari koefisien regresi yang bernilai positif dan signifikan. Maka pemerintah dapat berfokus pada upaya untuk mengurangi kemiskinan, guna mengurangi stunting.</p>
<p>Pemerintah dapat membuat aturan-aturan yang bertujuan untuk menekan kemiskinan, seperti program bantuan masyarakat, program penguatan masyarakat, dan program perluasan akses terhadap makanan sehat. Selain itu, Pemerintah dan organisasi non-pemerintah dapat menjalankan program-program yang bertujuan untuk menghindari dan menyembuhkan stunting, seperti program pemberian makanan pendamping, program edukasi gizi, dan program perbaikan akses terhadap layanan kesehatan.</p>
</section>
<section id="referensi" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="referensi"><span class="header-section-number">6</span> Referensi</h2>
<p>Damayanti, D. A., &amp; Sentosa, S. U. (2020). Analisis Kausalitas Stunting, Pertumbuhan Ekonomi dan Kemiskinan di Indonesia. Jurnal Kajian Ekonomi dan Pembangunan, 2(2), 45-48.</p>
<p>Sutarto, S. T. T., Mayasari, D., &amp; Indriyani, R. (2018). Stunting, Faktor ResikodanPencegahannya. Agromedicine Unila, 5(1), 540-545.</p>
<p>Ngaisyah, R. D. (2015). Hubungan sosial ekonomi dengan kejadian stunting pada balita di Desa Kanigoro, Saptosari, Gunung Kidul. Medika Respati: Jurnal Ilmiah Kesehatan, 10(4).</p>
<p>Rahmawati, N. F., Fajar, N. A., &amp; Idris, H. (2020). Faktor sosial, ekonomi, dan pemanfaatan posyandu dengan kejadian stunting balita keluarga miskin penerima PKH di Palembang. Jurnal Gizi Klinik Indonesia, 17(1), 23.</p>
<p>Sihite, N. W., &amp; Chaidir, M. S. (2022). Keterkaitan kemiskinan, kecukupan energi dan protein dengan kejadian stunting balita di Puskesmas 11 Ilir Palembang. Darussalam Nutrition Journal, 6(1), 37-47.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>